# -*- coding: utf-8 -*-
"""appp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M958SAKibbQSKE87Htp1RmYh1wJlz0pQ
"""

import streamlit as st
import cv2
import numpy as np
import os
import tempfile
import math
from ultralytics import YOLO
from deep_sort_realtime.deepsort_tracker import DeepSort

st.set_page_config(page_title="Accident Detection (YOLOv8 + DeepSORT)", layout="wide")
st.title("🚦 Accident Detection System (YOLOv8 + DeepSORT)")
st.markdown("""
Upload a **CCTV video** and the app will:
- Check if an accident occurred
- Explain **why** and **where**
- Show the **exact accident frame**
""")

# ---------------- Sidebar settings ----------------
st.sidebar.header("⚙️ Settings")
model_name = st.sidebar.selectbox("YOLOv8 model", ["yolov8n.pt", "yolov8s.pt", "yolov8m.pt"])
conf_thres = st.sidebar.slider("Detection confidence", 0.1, 0.9, 0.4, 0.05)
iou_thres = st.sidebar.slider("IOU threshold", 0.1, 0.6, 0.45, 0.05)
speed_drop_factor = st.sidebar.slider("Speed drop factor", 1.5, 5.0, 2.0, 0.1)
stationary_thresh = st.sidebar.slider("Stationary frame threshold", 10, 200, 30)
detect_classes = ["car", "bus", "truck", "motorcycle"]

# ---------------- Load YOLO model ----------------
@st.cache_resource
def load_model(name):
    return YOLO(name)

model = load_model(model_name)

@st.cache_resource
def get_tracker():
    return DeepSort(max_age=30, n_init=3)

tracker = get_tracker()

# ---------------- Helper functions ----------------
def iou(boxA, boxB):
    xA, yA = max(boxA[0], boxB[0]), max(boxA[1], boxB[1])
    xB, yB = min(boxA[2], boxB[2]), min(boxA[3], boxB[3])
    inter = max(0, xB - xA) * max(0, yB - yA)
    areaA = max(1, (boxA[2]-boxA[0])*(boxA[3]-boxA[1]))
    areaB = max(1, (boxB[2]-boxB[0])*(boxB[3]-boxB[1]))
    return inter / float(areaA + areaB - inter + 1e-6)

def region_in_frame(cx, width):
    third = width // 3
    if cx < third: return "Left"
    elif cx < 2 * third: return "Center"
    else: return "Right"

# ---------------- Accident detection ----------------
def analyze_video(video_path):
    cap = cv2.VideoCapture(video_path)
    fps = cap.get(cv2.CAP_PROP_FPS) or 25
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    frame_idx = 0

    track_history = {}
    accident_found = False
    accident_info = {}
    accident_frame_img = None
    progress = st.progress(0)

    while True:
        ret, frame = cap.read()
        if not ret:
            break
        frame_idx += 1

        # YOLO detection
        results = model(frame, conf=conf_thres, iou=iou_thres)[0]
        detections = []
        for box in results.boxes:
            cls_name = model.names[int(box.cls[0])].lower()
            if cls_name not in detect_classes:
                continue  # ✅ ignore non-vehicle detections
            x1, y1, x2, y2 = map(int, box.xyxy[0])
            conf = float(box.conf[0])
            detections.append(([x1, y1, x2, y2], conf, cls_name))

        # If no vehicles detected → skip
        if not detections:
            progress.progress(min(frame_idx / total_frames, 1.0))
            continue

        # DeepSORT tracking
        tracks = tracker.update_tracks(detections, frame=frame)
        current_tracks = []
        for t in tracks:
            if not t.is_confirmed():
                continue
            x1, y1, x2, y2 = map(int, t.to_ltrb())
            cx, cy = (x1 + x2) // 2, (y1 + y2) // 2
            tid = t.track_id
            track_history.setdefault(tid, []).append((frame_idx, cx, cy))
            current_tracks.append({"id": tid, "bbox": [x1, y1, x2, y2], "cx": cx, "cy": cy})

        # Accident logic
        for i in range(len(current_tracks)):
            for j in range(i+1, len(current_tracks)):
                A, B = current_tracks[i], current_tracks[j]
                overlap = iou(A["bbox"], B["bbox"])

                if overlap > 0.25:  # Significant overlap
                    aid, bid = A["id"], B["id"]
                    histA, histB = track_history.get(aid, []), track_history.get(bid, [])

                    def calc_speed(hist):
                        if len(hist) < 2: return 0
                        (f2,x2,y2), (f1,x1,y1) = hist[-1], hist[-2]
                        dt = max(1e-3, (f2-f1)/fps)
                        return math.hypot(x2-x1, y2-y1)/dt

                    spA, spB = calc_speed(histA), calc_speed(histB)

                    # Detect sudden stop + overlap → accident
                    if (spA > 3 and spB > 3) and abs(spA - spB) > speed_drop_factor:
                        accident_found = True
                        accident_info = {
                            "reason": "Collision between two vehicles (sudden overlap + speed drop)",
                            "frame": frame_idx,
                            "location": region_in_frame((A["cx"]+B["cx"])//2, width)
                        }
                        accident_frame_img = frame.copy()
                        cap.release()
                        progress.empty()
                        return True, accident_info, accident_frame_img

        progress.progress(min(frame_idx / total_frames, 1.0))

    cap.release()
    progress.empty()
    return False, {}, None

# ---------------- Streamlit frontend ----------------
uploaded = st.file_uploader("Upload a CCTV video", type=["mp4", "mov", "avi"])
run_btn = st.button("Run Accident Detection")

if uploaded and run_btn:
    tfile = tempfile.NamedTemporaryFile(delete=False)
    tfile.write(uploaded.read())
    video_path = tfile.name

    st.info("Processing video... please wait ⏳")
    has_accident, info, frame_img = analyze_video(video_path)

    if has_accident:
        st.error("🚨 Accident detected!")
        st.write(f"**Reason:** {info['reason']}")
        st.write(f"**Frame:** {info['frame']}")
        st.write(f"**Location:** {info['location']}")
        st.image(cv2.cvtColor(frame_img, cv2.COLOR_BGR2RGB), caption="Accident Frame", use_column_width=True)
    else:
        st.success("✅ No accident detected in this video.")